#!/usr/bin/env python3
"""Amalgamate a mathathon_kit submission into ONE self-contained .py file.

Most online judges accept only a single uploaded file, but a normal submission
does ``from mathathon_kit import ...`` / ``from examples.foo import ...``. This
tool inlines the whole ``mathathon_kit/`` package and every ``examples/`` module
into the output file and installs a tiny import hook so those imports keep
working with the original source unchanged.

Usage
-----
    python tools/bundle.py examples/platform_submission_nim.py
    python tools/bundle.py path/to/my_bot.py -o submission.py

Then verify the bundle behaves IDENTICALLY before uploading -- run it from a
directory that does NOT contain the repo so you prove it is self-contained:

    echo 21 | python submission.py

How it works
------------
The bundle stores each module's untouched source in a ``_BUNDLED_SOURCES`` dict
and registers a ``sys.meta_path`` finder that serves them. No import rewriting,
no dependency ordering -- relative imports inside the package just resolve.

The bundler inlines ``mathathon_kit/`` and ``examples/`` only. Keep your game
adapter inside ``examples/`` (or in the entry file itself) so it gets bundled.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]


_RUNTIME_TEMPLATE = '''\
#!/usr/bin/env python3
from __future__ import annotations
# ===========================================================================
# SELF-CONTAINED SUBMISSION -- generated by tools/bundle.py
# Entry: {entry_name}
# Do NOT edit by hand; change the source and re-run the bundler instead.
# ===========================================================================
import importlib.abc as _ia
import importlib.util as _iu
import sys as _sys

_BUNDLE_FILE = globals().get("__file__", "<bundle>")

_BUNDLED_SOURCES = {{
{sources}}}


class _BundleLoader(_ia.Loader):
    def __init__(self, name, source):
        self._name = name
        self._source = source

    def create_module(self, spec):
        return None

    def exec_module(self, module):
        # Give bundled modules a real __file__ so lines like
        # Path(__file__).resolve().parents[1] do not raise NameError.
        module.__file__ = _BUNDLE_FILE
        code = compile(self._source, "<bundle:%s>" % self._name, "exec")
        exec(code, module.__dict__)


class _BundleFinder(_ia.MetaPathFinder):
    def find_spec(self, fullname, path, target=None):
        if fullname not in _BUNDLED_SOURCES:
            return None
        is_pkg = any(k.startswith(fullname + ".") for k in _BUNDLED_SOURCES)
        return _iu.spec_from_loader(
            fullname,
            _BundleLoader(fullname, _BUNDLED_SOURCES[fullname]),
            is_package=is_pkg,
        )


if not any(type(_f).__name__ == "_BundleFinder" for _f in _sys.meta_path):
    _sys.meta_path.insert(0, _BundleFinder())

# ===========================================================================
# Entry module: {entry_name}
# ===========================================================================
{entry_body}
'''


def _module_name(path: Path, pkg: str, has_init: bool) -> str:
    """Dotted module name for a file inside package directory ``pkg``."""
    if has_init and path.stem == "__init__":
        return pkg
    return f"{pkg}.{path.stem}"


def _collect(pkg_dir: Path, pkg: str, exclude: Path) -> dict[str, str]:
    """Map every ``.py`` in ``pkg_dir`` to its dotted module name -> source."""
    if not pkg_dir.is_dir():
        return {}
    has_init = (pkg_dir / "__init__.py").exists()
    modules: dict[str, str] = {}
    for path in sorted(pkg_dir.glob("*.py")):
        if path.resolve() == exclude.resolve():
            continue  # the entry file is appended as __main__, not bundled
        modules[_module_name(path, pkg, has_init)] = path.read_text(encoding="utf-8")
    # A package without __init__.py still needs a key so `import examples`
    # resolves through our finder instead of hitting the real filesystem.
    if not has_init and modules:
        modules.setdefault(pkg, "")
    return modules


def _strip_future_imports(source: str) -> str:
    """Remove ``from __future__`` lines -- they are illegal mid-file and the
    generated bundle already declares the one it needs at the very top."""
    kept = [
        line
        for line in source.splitlines()
        if not line.lstrip().startswith("from __future__ import")
    ]
    return "\n".join(kept)


def build_bundle(entry: Path) -> str:
    entry = entry.resolve()
    if not entry.is_file():
        raise FileNotFoundError(f"entry script not found: {entry}")

    sources: dict[str, str] = {}
    sources.update(_collect(REPO_ROOT / "mathathon_kit", "mathathon_kit", entry))
    sources.update(_collect(REPO_ROOT / "examples", "examples", entry))
    if not sources:
        raise RuntimeError("found nothing to bundle -- run from the repo root")

    rendered = "".join(
        f"    {name!r}: {src!r},\n" for name, src in sorted(sources.items())
    )
    entry_rel = entry.relative_to(REPO_ROOT) if entry.is_relative_to(REPO_ROOT) else entry
    return _RUNTIME_TEMPLATE.format(
        entry_name=entry_rel.as_posix() if hasattr(entry_rel, "as_posix") else str(entry_rel),
        sources=rendered,
        entry_body=_strip_future_imports(entry.read_text(encoding="utf-8")),
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("entry", help="submission script to bundle (its imports get inlined)")
    parser.add_argument("-o", "--output", default="submission.py", help="output path (default: submission.py)")
    args = parser.parse_args(argv)

    bundle = build_bundle(Path(args.entry))
    out = Path(args.output)
    out.write_text(bundle, encoding="utf-8")
    kb = len(bundle.encode("utf-8")) / 1024
    print(f"wrote {out}  ({kb:.1f} KiB, {bundle.count(chr(10)) + 1} lines)")
    print(f"verify it from outside the repo:  python {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
